### ISSUE TITLE
Rider menu bar having wrong colour

### ISSUE THREAD

**Issue by bassepeder** [peppy/ppy-jetbrains-theme#4]
I don't know if this is intentional or not, but when watching your streams on Twitch, the Rider menu bar does not look like this. I'm using Windows (unfortunately 😅) so that may have an impact on this (?). 

![image](https://github.com/peppy/ppy-jetbrains-theme/assets/58905488/8f759101-f8b7-41a6-994f-53f08f4e5dd1)

**Comment by peppy** [comment]
If you mean the brown on the left, that's coming from your current project. In recent rider releases you can set a colour per project to differentiate between windows.

**Comment by bassepeder** [comment]
> If you mean the brown on the left, that's coming from your current project. In recent rider releases you can set a colour per project to differentiate between windows.

Sorry, I wasn't aware of that. Thanks.
